name: 'vib'
on: # rebuild any PRs and main branch changes
  pull_request_target:
    branches:
      - main
      - 7.12
    paths:
      - 'kibana/*'
env:
  CSP_API_URL: https://console.cloud.vmware.com
  CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
  VIB_PUBLIC_URL: https://cp.bromelia.vmware.com
jobs:
  vib-k8s-verify: # verify in multiple target platforms
    runs-on: ubuntu-latest
    environment: vmware-image-builder
    strategy:
      matrix:
       include:
         - target-platform: aks
           target-platform-id: 7b13a7bb-011c-474f-ad71-8152fc321b9e
      fail-fast: false
    name: K8s verify ${{ matrix.target-platform}}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: vmware-labs/vmware-image-builder-action@main
        with:
          pipeline: vib-platform-verify-kibana.json
        env:
          TARGET_PLATFORM: ${{ matrix.target-platform-id }}
